### ISSUE TITLE
Changing browser zoom breaks Scrollama progress updates

### ISSUE THREAD

**Issue by jimjam-slam** [qmd-lab/closeread#101]
On https://closeread.netlify.app/gallery/demos/ojs-variables, scroll part way through the OJS animation, then change browser zoom and continue to scroll. The Scrollama progress variables no longer update.

Perhaps Scrollama needs to be rebooted or some such when browser zoom changes?

Observed on Safari and Chrome (and I've just realised that the OJS demo fails entirely on Chrome! 🪦)

**Comment by andrewpbray** [comment]
Oy! Indeed, on Chrome:

<img width="800" alt="Screenshot 2024-10-19 at 5 48 41 PM" src="https://github.com/user-attachments/assets/6b157fbe-65a3-4297-9269-3127fde71914">

Do you think this is a browser update that broke this? I swear this one was working fine on chrome a week ago..

**Comment by jimjam-slam** [comment]
Interesting! I wonder if the Quarto team are getting any reports... should be on in just over an hour to get into it!

**Comment by jimjam-slam** [comment]
I've split the GeoJSON error out to a separate issue (but it looks like it's no longer a problem on the preview docs!).

For the animation, I can confirm that the step progress and step enter events don't appear to be firing properly. See attached video:

https://github.com/user-attachments/assets/2de75b11-55a7-4e80-b28d-34b7da34f577

I might see if I can refactor our code very slightly so that the Scrollama event listeners are "rebooted" when the screen zoom changes!

**Comment by jimjam-slam** [comment]
I think this might be https://github.com/russellsamora/scrollama/issues/145. I've attempted a small change based on a [comment](https://github.com/russellsamora/scrollama/issues/145#issuecomment-1764582014) in that thread:

```
# after the scroller setup code

window.addEventListener("resize", (event) => {
    console.log(">>> WINDOW RESIZE")
    setTimeout(1000, triggerScroller.resize)
    setTimeout(1000, progressBlockScroller.resize)
  })
```

I used `setTimeout` instead of `debounce` from the `throttleDebounce` library on the assumption that it's purely a performance consideration to not want to call it many times. But I'm not seeing any success. Not sure if there's a race condition, if this just isn't the problem or something in the middle.

**Comment by jimjam-slam** [comment]
Not sure if it's necessary to bring in `throttle-debounce` and use that — performance doesn't seem to be _massively_ affected when manually resizing the window, and a browser zoom only seems to cause one resize event. (That said, I'd like to get more _au faix_ with ES Modules so we can start leaning on a few more things :) )
