### ISSUE TITLE
GeoJSON 404 on published docs

### ISSUE THREAD

**Issue by jimjam-slam** [qmd-lab/closeread#105]
> Oy! Indeed, on Chrome:
> 
> <img width="800" alt="Screenshot 2024-10-19 at 5 48 41 PM" src="https://github.com/user-attachments/assets/6b157fbe-65a3-4297-9269-3127fde71914">
> 
> Do you think this is a browser update that broke this? I swear this one was working fine on chrome a week ago..
> 
_Originally posted by @andrewpbray in https://github.com/qmd-lab/closeread/issues/101#issuecomment-2424357157_

**Comment by jimjam-slam** [comment]
This is actually working locally, and on the published docs the console is showing a 404 for the GeoJSON file. So I'm thinking maybe we've just forgotten to add it to the site resources somehow.

**Comment by jimjam-slam** [comment]
The GeoJSON file actually appears correctly in `_site` when I render locally even if I don't specify it in the `resources` key. I thought maybe there could be a difference in how site resources are handled between Quarto release (in the GHA) and my local prerelease, but the GeoJSON file still seems to make it even when I check out Quarto v.1.5.57 and render 🤔


 so maybe the logic for including default site resources has been tightened up between the Quarto latest release (which it looks like the container uses?) and the Quarto prerelease (which I'm running locally)

**Comment by jimjam-slam** [comment]
Actually this is fine on [the preview docs](https://preview.closeread.dev/gallery/demos/ojs-variables)! It only occurs on [the main docs](https://preview.closeread.dev/gallery/demos/ojs-variables). Not sure if there's a Quarto version difference between them or a file difference...

**Comment by jimjam-slam** [comment]
Even weirder — no difference in the OJS demo's `index.qmd` or  the project `_quarto.yml` between `main` and `dev` branches 🤔

```
$ git diff dev main -- docs/gallery/demos/ojs-variables/index.qmd | cat
$ git diff dev main -- docs/_quarto.yml | cat
```

**Comment by andrewpbray** [comment]
It looks like closeread.dev (nee closeread.netlify.app) hasn't been updated since mid August, so. I'm on a pre-release and it works fine, so I'll publish from local using the same command as the action: `quarto publish netlify docs --id 2a052dac-9a3d-43c1-9f3d-e37e3cb55af2`.

**Comment by jimjam-slam** [comment]
@andrewpbray Could this have been the same issue as the missing image when we visited a page on Netlify without the trailing space?

**Comment by andrewpbray** [comment]
Might well be!
