### ISSUE TITLE
themeing is broken on closeread.dev

### ISSUE THREAD

**Issue by andrewpbray** [qmd-lab/closeread#111]
The pages in the gallery (which run their own css) have a different nav bar than the main page:

![cosmo](https://github.com/user-attachments/assets/5ff91d3b-e10a-477b-bed3-4e424c097452)

![nyt](https://github.com/user-attachments/assets/31c363bc-f39c-4afc-93e2-69dbd87c4dc1)

Looks like the `cosmo` theme isn't percolating down to these pages (the blue navbar is the default I believe).

Maybe we didn't run `sass` before merging? That'd be a good thing to put on CI I guess? (not sure if `sass` is on the image)

**Comment by jimjam-slam** [comment]
Mmm, I hadn't thought about that! I'll try to take a look at this one later tonight 🤔

**Comment by jimjam-slam** [comment]
For this one, I think we just need to move `_metadata.yml` from `/docs/gallery/demos/_metadata.yml` to `/docs/gallery/_metadata.yml`!
