### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by gkaramanis** [qmd-lab/closeread#80]
Feel free to delete this, I only wanted to say thank you for Closeread and Sverto and your great presentations at posit::conf!

I've started playing with Closeread and is super fun, I'll be following its development!

**Comment by jimjam-slam** [comment]
Thanks so much, Georgios! I got to watch @andrewpbray's talk online, and he knocked it outta the park imho 😉 We're both keen to keep making Closeread better!

**Comment by gkaramanis** [comment]
Looking forward to it! Here's the repo of my first story if you want to have a look 😃 

https://github.com/gkaramanis/tidytuesday/tree/master/2024/2024-week_33

**Comment by andrewpbray** [comment]
That's awesome - thanks for reaching out and sharing your work! It's so gratifying to see what others can do with these tools.
