### ISSUE TITLE
Examples from the guide not working?

### ISSUE THREAD

**Issue by gkaramanis** [qmd-lab/closeread#85]
I can't seem to make the examples from the guide to work, like highlighting. I hope it's just my jet-lagged brain missing something simple! 😅 

<img width="771" alt="Screenshot 2024-08-19 at 14 40 30" src="https://github.com/user-attachments/assets/2192f45a-1b5b-47b0-bf72-f698d4543b06">
<img width="629" alt="Screenshot 2024-08-19 at 14 40 44" src="https://github.com/user-attachments/assets/1b29602c-33c0-49d5-b83a-360900e88292">

**Comment by kpivert** [comment]
Hey @gkaramanis , I experienced the same thing when I walked through the docs, but when you wrap it within the `::::{.cr-section}
<code>
::::` it works. 
Great to meet you!
Kurtis

**Comment by andrewpbray** [comment]
Yep, I think there are two things here:

As @kpivert mentions, all the closeread features must be wrapped in a div with `.cr-section`.

The other thing, though, is that that the documented use cases for highlighting code is for the source code, not the output. So you'll want to add `#| echo: true` to your code cell. Note that allowing for focus effects on code output is our top priority (track the issue in #78 ). We'll be doing some develop and hopefully fixing this in about a week an half!

**Comment by gkaramanis** [comment]
Thank you both, it makes perfect sense!
