### ISSUE TITLE
Vestigial filter in .lua

### ISSUE THREAD

**Issue by andrewpbray** [qmd-lab/closeread#94]
This isn't the solution to the problem, but while looking at the Lua I found this at the very bottom of the file

https://github.com/qmd-lab/closeread/blob/d5583d1c41abd2eb3f8673b403b522c178dbb537/_extensions/closeread/closeread.lua#L519

As far as I can tell, I don't think that's actually a function that we define?

I'm just recording that here for now.

_Originally posted by @andrewpbray in https://github.com/qmd-lab/closeread/issues/82#issuecomment-2378014407_

**Comment by jimjam-slam** [comment]
Mmm, I noticed that! Can confirm it doesn't affect the other issue and doesn't appear to be linked to anything (but doesn't some to affect everything else running either).
